### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by vincentchalamon** [olaurendeau/RabbitMqAdminToolkitBundle#5]
Hi,

It should be useful to check a Symfony 3 compatibility :)
- [ ] Update dependencies
- [ ] Check tests
- [ ] Check deprecations

**Comment by MLKiiwy** [comment]
:+1: and yeah @olaurendeau now we use symfony 3 at lafourchette :P

**Comment by vincentchalamon** [comment]
This library can be installed on a Symfony 3 project, but better to check its compatibility :wink:

**Comment by olaurendeau** [comment]
Hello guyz :)
It's already compatible since v1.2.1 : https://github.com/olaurendeau/RabbitMqAdminToolkitBundle/releases/tag/v1.2.1
Build : https://travis-ci.org/olaurendeau/RabbitMqAdminToolkitBundle
Used here with SF3 https://github.com/olaurendeau/rabbitmq-demo
BTW @vincentchalamon thanks for your dockerized symfony env :+1:

**Comment by vincentchalamon** [comment]
Thanks @olaurendeau :)
